### ISSUE TITLE
Make preprocessing fully differentiable with torch API

### ISSUE THREAD

**Issue by HudsonHuang** [yistLin/dvector#4]
I appreciate your efforts, nice work.
But your [audio_toolkit](https://github.com/yistLin/dvector/blob/631a19abafca40bb2a00a6829f0572c717526ede/data/audio_toolkit.py#L32) was implement in librosa and numpy, which was not differentiable.
It might limited the application. Eg. If I have an TTS model to generated Mel spectrogram, and if your dvector if fully differentiable, we can use this like a discriminator, to force the TTS model output exactly as expected person.
From waveform to Melspectrogram, you can make preprocessing fully differentiable with  [torchaudio](https://github.com/pytorch/audio), and [it seems it can keep consitency with librosa](https://github.com/pytorch/audio/blob/master/test/torchaudio_unittest/README.md)

**Comment by yistLin** [comment]
Hi, thanks for your suggestion. I'm actually considering ditching `librosa` for `torchaudio` especially after I chose to do silence trimming with `sox` instead of `webrtcvad`.

Since I'd like to make the preprocessing modules as simple as possible (import less packages as possible), I probably need some time to study the usage of sox effects in the most recent version of `torchaudio`.

**Comment by yistLin** [comment]
I've developed completely new preprocessing toolkits which use `torchaudio`, can be compiled with *TorchScript* and be used anywhere without any dependencies.
